language: python
python: "3.7"
dist: xenial
sudo: required
cache: pip

services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database evap;' -U postgres
install:
  - pip install -r requirements-travis.txt
  - echo 'SECRET_KEY = "evap-travis-secret-key"' >> evap/localsettings.py

env:
  - COMMAND="pylint evap -j 0"
  - COMMAND="deployment/test_backup_and_restore_on_travis.sh"
  - COMMAND="coverage run manage.py test && coveralls"
  - COMMAND="python manage.py test --debug-mode"
  - COMMAND="python manage.py test --reverse"
script:
  - eval $COMMAND
